opendp/dp-wizard

- dp_creator_ii/template.py
- dp_creator_ii/tests/test_template.py
> Simplify the template syntax

- README.md
> Add pointers to playwright docs

- dp_creator_ii/app.py
- dp_creator_ii/app/dataset_panel.py
- dp_creator_ii/tests/test_app.py
- I'd suggest first merging #17
- Fix #9 
- Fix #10
> Strengthen end-to-end test

- requirements-dev.txt
- Fix https://github.com/opendp/dp-creator-ii/security/dependabot/1
More changes than are strictly necessary. Latter on, we'd probably be more careful about an update across the board, but right now it is low risk.
> rebuild requirements-dev.txt

- dp_creator_ii/app/analysis_panel.py
- dp_creator_ii/app/css/styles.css
- Fix #25
Feels hacky, but does what we need.
> Logarithmic epsilon slider

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/maybe-next.md
- .github/ISSUE_TEMPLATE/nice-to-have.md
- .github/ISSUE_TEMPLATE/poc.md
- .github/ISSUE_TEMPLATE/question.md
> Issue templates

- dp_creator_ii/utils/argparse_helpers.py
> pytest -vv works now

- dp_creator_ii/app/components/plots.py
The exact cutoff might change.
- Fix #128
Time: ~1 hour
> Do not label every bin

- requirements-dev.in
- requirements-dev.txt
- Fix https://github.com/opendp/dp-wizard/security/dependabot/2
> Upgrade all dependencies

- README.md
> just use plain pip install

- README.md
- tests/test_app.py
> warn about breakpoint in playwright

- dp_wizard/utils/code_generators/__init__.py
- dp_wizard/utils/code_generators/no-tests/_notebook.py
> Remove extra dash and commented-out code

- dp_wizard/utils/shared.py
- fix #210
It's going to be hard to get a simple solution that works in all cases, but this might help.
> Maybe changing the aspect ratio helps?

- dp_wizard/utils/shared.py
> simplify plotting: No major/minor; instead angle the x-axis labels

- dp_wizard/app/results_panel.py
- tests/test_app.py
- Fix #246
This isn't a super high priority, but it also seems like an easy addition which could be useful.
There's a lot of redundancy in the function definitions, but reactive calcs don't take parameters, so this seems like an ok approach, but open to suggestions.
> download unexecuted notebooks

- .pytest.ini
- dp_wizard/utils/converters.py
- tests/utils/test_converters.py
> lower the logging level if kernel needs install

- dp_wizard/utils/code_generators/__init__.py
> pyyaml does not need to be installed in notebook

- dp_wizard/app/__init__.py
- dp_wizard/app/dataset_panel.py
- tests/test_app.py
- Fix #273
... I think: This is complicated, I could have missed something.
> Only access CLIInfo from server

- dp_wizard/analyses/protocol.py
- dp_wizard/app/components/inputs.py
- tests/test_app.py
> Hacky CSS for a better epsilon slider

- .github/ISSUE_TEMPLATE/bug-back.md
- .github/ISSUE_TEMPLATE/bug-front.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/maybe-next.md
- .github/ISSUE_TEMPLATE/nice-to-have.md
- .github/ISSUE_TEMPLATE/question.md
- README-PYPI.md
- README.md
- Fix #307 
- Fix #308 
Largely in response to Annie's comments, so I should get feedback from her.
> Issue templates and an invitation to contribute

- pyproject.toml
> provide command line alias

- dp_wizard/app/about_panel.py
> Use 2nd person on about tab

- .github/ISSUE_TEMPLATE/question.md
- pyproject.toml
- tests/test_misc.py
> Add more metadata

- .github/ISSUE_TEMPLATE/bug-back.md
- .github/ISSUE_TEMPLATE/bug-front.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
> add types on issue templates

- README.md
> list of outside resources

- dp_wizard/utils/code_generators/no-tests/_privacy_loss.py
> line wrap privacy loss code sample

- dp_wizard/app/analysis_panel.py
- dp_wizard/utils/code_generators/no-tests/_privacy_loss.py
- Fix #365
... but is this even a good idea? For this, and for a lot of other issues, I don't think the full design review process that we had at the start of the project is necessary, but it's also possible that this isn't the right direction. Maybe the emphasis should be on explaining the epsilon choice in this application, rather than foisting that responsibility on to another project?
> Link to epsilon registry

- dp_wizard/shiny/results_panel.py
- tests/test_app.py
- Fix #313
- Doesn't include grouping, or any of the parameters, but I don't think it should include everything. feedback welcome!
- one mime type fix
> informative download file names

- dp_wizard/shiny/results_panel.py
- Fix #420
This PR doesn't add any messaging about _why_ the buttons are disabled: That is handled in #417.
> Disable downloads if analysis undefined

- dp_wizard/utils/code_generators/no-tests/_notebook.py
> OpenDP -> "the OpenDP library"

- dp_wizard/shiny/results_panel.py
- dp_wizard/utils/converters.py
- tests/fixtures/fake-executed.ipynb
- tests/fixtures/fake.ipynb
- tests/utils/test_converters.py
> html <title> in notebook

- README-PYPI.md
- README.md
- dp_wizard/shiny/about_panel.py
- dp_wizard/shiny/components/column_module.py
- dp_wizard/shiny/dataset_panel.py
- dp_wizard/shiny/results_panel.py
- dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_expr.py
- dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_expr.py
- dp_wizard/utils/code_generators/analyses/median/no-tests/_median_expr.py
- dp_wizard/utils/code_generators/no-tests/_context.py
- dp_wizard/utils/code_generators/no-tests/_imports.py
- dp_wizard/utils/code_generators/no-tests/_notebook.py
- tests/utils/test_code_generators.py
- Fix #406
- respond to [comment from Mike](https://github.com/opendp/dp-wizard/commit/842bc95be7557884548504c2540983830dcd4ede#diff-2568976890f6f013d6e4c6421a898839ddd10d59e989d1b3fac84e902191de2aR3)
> capital "L" in "Library"

- dp_wizard/utils/code_generators/no-tests/_notebook.py
> remove reference to "Queryable"

- dp_wizard/shiny/results_panel.py
- dp_wizard/utils/converters.py
> Python executable might not be named "python"

- README.md
> Correction to release process: Pull out highlights

- dp_wizard/shiny/analysis_panel.py
- dp_wizard/shiny/components/column_module.py
- Fix #467 
- Analogous to #508
> Changing contributions no longer resets analysis parameters

- dp_wizard/utils/code_generators/__init__.py
> more info in generated code about parameters, particularly delta

- dp_wizard/shiny/components/column_module.py
- dp_wizard/shiny/components/outputs.py
- dp_wizard/shiny/dataset_panel.py
- tests/test_app.py
- Fix #513
We could also use this for a comment in the generated notebook, but this seems like enough for now?
> Two step unit of privacy

- dp_wizard/__init__.py
- dp_wizard/utils/code_generators/__init__.py
- dp_wizard/utils/code_generators/abstract_generator.py
- dp_wizard/utils/code_generators/analyses/count/__init__.py
- dp_wizard/utils/code_generators/analyses/count/no-tests/_count_expr.py
- dp_wizard/utils/code_generators/analyses/histogram/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_expr.py
- dp_wizard/utils/code_generators/analyses/mean/__init__.py
- dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_expr.py
- dp_wizard/utils/code_generators/analyses/median/__init__.py
- dp_wizard/utils/code_generators/analyses/median/no-tests/_median_expr.py
- dp_wizard/utils/code_generators/no-tests/_context.py
- tests/test_misc.py
- tests/utils/test_code_generators.py
> Pin doc links

- dp_wizard/shiny/__init__.py
- Fix #438
Just something that makes life easier for developers.
> Check that IDs match on startup

- dp_wizard/utils/code_generators/abstract_generator.py
- dp_wizard/utils/code_generators/analyses/__init__.py
- dp_wizard/utils/code_generators/analyses/count/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/__init__.py
- dp_wizard/utils/code_generators/analyses/mean/__init__.py
- dp_wizard/utils/code_generators/analyses/median/__init__.py
> make has_bins a property

- dp_wizard/shiny/components/column_module.py
- dp_wizard/utils/code_template.py
- Fix #519
Low priority. I'd suggest waiting on this until after the release.
> Remove unneeded "else"s

- dp_wizard/shiny/__init__.py
- dp_wizard/shiny/analysis_panel.py
- dp_wizard/shiny/components/column_module.py
- dp_wizard/shiny/dataset_panel.py
- dp_wizard/shiny/results_panel.py
- dp_wizard/types.py
- dp_wizard/utils/code_generators/__init__.py
- dp_wizard/utils/code_generators/abstract_generator.py
- dp_wizard/utils/code_generators/analyses/__init__.py
- dp_wizard/utils/code_generators/analyses/count/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_notebook_output.py
- dp_wizard/utils/code_generators/analyses/mean/__init__.py
- dp_wizard/utils/code_generators/analyses/median/__init__.py
- dp_wizard/utils/code_generators/notebook_generator.py
- dp_wizard/utils/csv_helper.py
- tests/test_app.py
- tests/utils/test_code_generators.py
- Fix #539
- Fix #537
- Replaces #540
> Stronger typing: `AnalysisName` and `ColumnName`

- dp_wizard/shiny/dataset_panel.py
> add a placholder, so both inputs are the same width

- pyproject.toml
- requirements-dev.txt
- requirements.in
- requirements.txt
> Upgrade starlette

- dp_wizard/shiny/__init__.py
- dp_wizard/shiny/analysis_panel.py
- dp_wizard/shiny/components/column_module.py
- dp_wizard/shiny/components/outputs.py
- dp_wizard/shiny/dataset_panel.py
- dp_wizard/shiny/results_panel.py
- tests/test_app.py
> Make the demo tooltips always-on

- README.md
> replace zoom with email

- dp_wizard/shiny/dataset_panel.py
- dp_wizard/utils/code_generators/__init__.py
- dp_wizard/utils/code_generators/abstract_generator.py
- dp_wizard/utils/code_generators/analyses/count/__init__.py
- dp_wizard/utils/code_generators/analyses/count/no-tests/_count_expr.py
- dp_wizard/utils/code_generators/analyses/histogram/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_expr.py
- dp_wizard/utils/code_generators/analyses/mean/__init__.py
- dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_expr.py
- dp_wizard/utils/code_generators/analyses/median/__init__.py
- dp_wizard/utils/code_generators/analyses/median/no-tests/_median_expr.py
- dp_wizard/utils/code_generators/no-tests/_stats_context.py
- dp_wizard/utils/code_generators/no-tests/_synth_context.py
- dp_wizard/utils/code_generators/no-tests/_synth_notebook.py
- dp_wizard/utils/code_generators/script_generator.py
- tests/utils/test_code_generators.py
This will be rendered into both the notebook and the script output: Since the output isn't captured by the script, it's not really doing anything, but it is still useful to point out that it exists.
- Fix #601
Also realized docs links were broken. Fixed now, but it would be better to check automatically.
- see: #547
> Demo `project_melted()`

- dp_wizard/shiny/assets/styles.css
- dp_wizard/shiny/components/outputs.py
- dp_wizard/shiny/results_panel.py
- tests/test_app.py
- Fix #469
(Title inside the notebook is still automatic, and that seems ok to me.)
> User can set download name

- dp_wizard/utils/code_generators/analyses/count/no-tests/_count_expr.py
- dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_expr.py
- dp_wizard/utils/code_generators/analyses/median/no-tests/_median_expr.py
- tests/utils/test_code_generators.py
> Remove `fill_nan` and `fill_null`

- dp_wizard/shiny/components/column_module.py
- dp_wizard/shiny/components/inputs.py
- dp_wizard/shiny/dataset_panel.py
> fill in labels for screenreaders

- dp_wizard/utils/code_generators/analyses/count/__init__.py
- dp_wizard/utils/code_generators/analyses/count/no-tests/_count_query.py
- dp_wizard/utils/code_generators/analyses/histogram/__init__.py
- dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_query.py
- dp_wizard/utils/code_generators/analyses/mean/__init__.py
- dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_query.py
- dp_wizard/utils/code_generators/analyses/median/__init__.py
- dp_wizard/utils/code_generators/analyses/median/no-tests/_median_query.py
I was going to work on the queries, but I found bouncing between files confusing. Hope this is an improvement, but it is subjective.
- Towards #630
> Inline query templates

- dp_wizard/utils/csv_helper.py
- Fix #596
Easiest just not to allow columns without headers to be selected.
> exclude columns which are missing headers
