opendp/dp-wizard

dp_creator_ii/templates/context.py
dp_creator_ii/tests/test_csv.py
dp_creator_ii/tests/test_template.py

- Fix #8 (Added some notes about alternative approaches there.)
The proposal here is just to include `encoding="utf8-lossy"` when we read CSVs, and not even bother with trying to figure out the correct encoding, because it will usually not matter.

Handle non-utf8 CSVs

---

README.md
dp_creator_ii/.gitignore
dp_creator_ii/__init__.py
dp_creator_ii/app.py
dp_creator_ii/tests/test_help.py

- Fix #6
- Drop the `--debug` flag and make watching the filesystem the default, and keep the default log level. We can revisit this when there's a need.
- Move arg parsing down inside the app, and get rid of hacky `config.json`: `sys.argv` is accessible everywhere, so just wait to parse until the app has started.

Fix auto reload and simplify argument handling

---

pyproject.toml
requirements-dev.in
requirements-dev.txt

- fix #43
I had introduced this dependency copy-and-pasting from tutorials, but we don't need it, and may never need it. It allows interactive widgets designed for Jupiter to work in Shiny.
Even if they come for free, I'm inclined to keep interactive visualizations out of this project. Producing PDFs at some point isn't unlikely, and dealing with interactive visualizations would be a distraction.

Remove shinywidgets

---

.pytest.ini
README.md
dp_creator_ii/__init__.py
dp_creator_ii/app/dataset_panel.py
dp_creator_ii/argparse_helpers.py
dp_creator_ii/tests/test_arg_parser.py

- extract fake csv creation from #48: Once this is merged to main, I would plan to merge main to that branch, and remove the code from the notebook that is now covered here.
- Fix #7 (though we don't do anything with the data yet)
- enable doctests
- Consolidate arg parsing and demo dataset creation in one file
- Related to #51, but don't think it really fixes it.
There are a few `pragma: no cover` notes scattered over this where we are missing test coverage. If you want to hold this to a higher standard, I wouldn't object, but I think this is sufficient for now.

Add `--demo` CLI option

---

README.md

I'm guessing about how some of these transitions work, so if you have something else in mind, please suggest changes.

Status flow chart

---

dp_creator_ii/utils/csv_helper.py
tests/test_csv.py

This improves our handling of different encodings, but it also involves using polars to read data when we just need the column headers.
- Fix #79

Improve handling of different encodings

---

.github/workflows/test.yml

- Fix #20
- CI download time might not be the most important thing to optimize: We could just drop this and close the issue. Thoughts?
- Another option, and probably not necessary for us, would be to configure a matrix and confirm that different browsers work.

Only install Chromium

---

README.md
WHAT-WE-LEARNED.md

- Fix #118 
Will add to this going forward.

What we learned

---

dp_creator_ii/__init__.py
dp_creator_ii/app/__init__.py
dp_creator_ii/app/dataset_panel.py
dp_creator_ii/utils/argparse_helpers.py
tests/fixtures/default_app.py
tests/fixtures/demo_app.py
tests/test_app.py

- Fix #105
Initially tried to use mocking for this, but couldn't get it to work.
- Filed #119 
... but in the end, I think this is a pretty clear approach.
When we handle this:
- #113
expand the test.

Playwright test for `--demo`

---

dp_creator_ii/app/analysis_panel.py
dp_creator_ii/app/dataset_panel.py
tests/test_app.py

Disable buttons until required inputs supplied

---

WHAT-WE-LEARNED.md
dp_creator_ii/app/components/column_module.py
dp_creator_ii/app/css/styles.css

- Fix #131 
- Close #132 without fix: There is plenty of vertical space, and it's not immediately obvious from the docs how to get the label and the input on the same line.
- Demoing for Annie, and she would prefer a wider page margin, so I tweaked that. I still hope there is a "right" way to do this that extends the tab line to the edge of the window, but I don't have that solution right now.
I would also like to avoid repeating the warning above the graph, but that's more of a logic change, so don't worry about it right now.
- #138
Working with this part of the UI prompted me to file a new issue:
- #136
Time required: ~1 hour

Two column layout: Graph expands to fit

---

dp_wizard/tmp/.gitignore
dp_wizard/utils/argparse_helpers.py

- Fix #141 
- Replace #146
Might also use this for uploaded files. Currently if you upload a file through the UI, the path is a really obscure temp directory, and that's what we end up showing in the notebook. A scratch space that's local to the code might be a better solution.

Write to a relative temp dir

---

dp_wizard/app/analysis_panel.py
dp_wizard/app/components/column_module.py
dp_wizard/utils/code_generators/__init__.py
dp_wizard/utils/dp_helper.py

- Fix #153.
- My sense is that the confidence interval is not something we want to control in the UI: It's the kind of detail that is best left for the user to tweak in the notebook.
For the reviewer:
- Does a short comment in the UI (where we want to avoid distractions) and a longer note in the notebook (where we want to really explain things) make sense?
- Do you think explanation is needed anywhere else? Could add a comment to the graphs, but I'd worry about clutter.

Explain confidence interval

---

WHAT-WE-LEARNED.md
dp_wizard/app/analysis_panel.py
dp_wizard/app/components/column_module.py
dp_wizard/app/components/outputs.py
tests/test_app.py

- Fix #136
Shiny doesn't seem to support disabling select controls. Not in the docs, and just adding a kwarg doesn't work. Adding a note after the control follows the pattern we have with disabled buttons. For both of these styling it as a [bootstrap alert](https://getbootstrap.com/docs/4.0/components/alerts/) might be appropriate.
For reviewer:
- Does this message seem worthwhile? or maybe it's a distraction if we can't easily disable the select?
- Would styling this message as an alert be appropriate? or would that call too much attention to it?
On the whole I think this is a good change, but I'm not totally confident about it. Feedback welcome.
---
Update: Instead of adding a message, just use a hidden div when there is only one column selected. PR retitled.

Hide weight if only one column selected

---

dp_wizard/app/analysis_panel.py
dp_wizard/app/components/column_module.py
dp_wizard/utils/dp_helper.py
tests/test_app.py

- Fix #154
For the reviewer:
- Does the introduction to this option make sense?
- Is this a good set of choices? I was hoping that thinking in terms of orders of magnitude lessens the pressure on the user when coming up with an estimate, and that 10 is too small to be useful, while 100,000 is so large that the improvement is negligible, leaving us with 100, 1,000, and 10,000.

Let user set number of rows in simulated data

---

dp_wizard/app/results_panel.py
dp_wizard/tmp/.gitignore
dp_wizard/utils/code_generators/__init__.py
dp_wizard/utils/code_generators/no-tests/_report_kv.py
dp_wizard/utils/code_generators/no-tests/_reports.py
tests/test_app.py

- Fix #172
- also put all the download buttons in a grid with icons
Not committed to this format for the reports: Just heard that there should be a CSV, but there don't seem to be be any requirements beyond that.

CSV report

---

dp_wizard/app/analysis_panel.py
dp_wizard/app/components/column_module.py
tests/test_app.py

- Towards #94
- Wrap each column interface in a card.
- Use the space at the top more efficiently, too.
- The formatting of the slider isn't great, but if the overall layout here seems like an improvement, I'd like to leave that for later.
For reviewer:
- This is subjective, but does this seem to present the steps in defining the analysis a little more clearly?

Add cards on analysis page

---

README-PYPI.md
pyproject.toml
tests/test_app.py
tests/utils/test_argparse_helpers.py

add readme for pypi

---

README.md
dp_wizard/utils/code_generators/__init__.py

Link to pypi

---

dp_wizard/utils/code_generators/__init__.py
dp_wizard/utils/code_generators/no-tests/_notebook.py
dp_wizard/utils/code_generators/no-tests/_script.py

- Fix #166 
Having a separate requirements.txt with the script feels like overkill.
We also don't have a test that confirms that the given dependencies are sufficient, but that also feels like overkill.

Document dependencies in generated code

---

dp_wizard/utils/code_generators/no-tests/_query.py
dp_wizard/utils/dp_helper.py

move it out of the code, but add it to the doctest for stability.
- Fix #178

Remove unused sort

---

dp_wizard/app/__init__.py
dp_wizard/app/analysis_panel.py
dp_wizard/app/components/column_module.py
dp_wizard/utils/dp_helper.py
tests/test_app.py

- Fix #203 
- Fix #122
Previously, the generation of the fake data and rendering were in the same function. This pulls the generation of fake data into a separate reactive calc that gets called from several different functions.
For the reviewer:
- Are the UI and layout reasonable?
- The app is getting more complicated, but none of the complexity really has anything to do with DP. Is this codebase going to be maintainable by people other than Chuck?

confidence interval text + histogram table

---

dp_wizard/app/components/outputs.py
dp_wizard/app/dataset_panel.py
tests/test_app.py

- Fix #188
The user could also misfill Upper/Lower/Bins on the next tab, but in that case, there is an immediate error message, albeit an ugly one, so I'm inclined not to add more validation code there. 
For reviewer:
- Is this UI good enough?
- Ok not to investigate test flakiness (`define_analysis_button.is_disabled()`) more deeply?
- Confirmation that we're ok with Shiny's default error messages, where the error is obviously connected to the input?

Validate contributions

---

dp_wizard/utils/converters.py
tests/utils/test_converters.py

- Fix #222
Note that [warnings.warn()](https://docs.python.org/3/library/warnings.html#warnings.warn) != [Logger.warning()](https://docs.python.org/3/library/logging.html#logging.Logger.warning). The former is what we're using.

Capture and show any error messages from notebook execution

---

dp_wizard/utils/shared.py
tests/utils/test_shared.py

- Fix #238
- Will help with #237 
The idea is that rather than sorting out right now the details of how visualization will work when we have more keys (ie, should it be multiple plots? Or groups of columns? Or stacked columns? ...), we just concatenate the keys, and everything downstream works the same as before: Just one plain bar chart.
This code is included in the final notebook, and it is getting a little long, so move the test out.

Handle more columns in dataframe helper

---

dp_wizard/app/analysis_panel.py

An alternative to this PR is to have two independent clauses. Something like this:
"Groups aren't applied to the previews on this page, but they will be used in the final release."
https://www.grammar-monster.com/glossary/compound_predicate.htm

no commas in compound predicates

---

.github/workflows/test.yml
ci.sh
dp_wizard/utils/argparse_helpers.py
dp_wizard/utils/converters.py
requirements-dev.in
requirements-dev.txt
tests/utils/test_argparse_helpers.py

- Fix #261
Tests run about twice as fast locally with this change. In the future, might improve this further by splitting up slow end-to-end tests.
Had one failure on CI that went away with a re-run: not sure if there's a deeper problem.
If this seems like a good change for developers, but a source of added complexity in CI, one option would be to make the behavior of `ci.sh` conditional. Open to suggestions.

Use xdist for parallel tests

---

dp_wizard/utils/converters.py
tests/utils/test_converters.py

- Fix #277
In the state before this PR, if there actually is an error in the generated code, it's hard to debug because we hide the warning, on the chance that the root problem is just a missing kernel.
The logic is simplified here, and we first check if the kernel is installed explicitly, and install if not, and then move on.

check for kernel first, instead of falling back

---

README-PYPI.md
dp_wizard/app/__init__.py
dp_wizard/app/about_panel.py
dp_wizard/app/dataset_panel.py
tests/test_app.py

- Replaces #282
- Fix #272
I would like to keep this short, and if there is important information about what this application does, then it really belongs in a README: Users shouldn't need to install to get this information.
The situation is different from DP Creator. This, at present, is a single user application, and the user found and installed it themselves. It is not embedded in a larger application.
I would strongly prefer that most users not be slowed down by this. If there's a request that this be on a splash screen on the first run, I'd prefer to tackle that as a follow-up.
About pages often do include version numbers, particularly to help users filing issues, so I've included that here as well.

Add "about" tab

---

dp_wizard/app/results_panel.py
dp_wizard/utils/code_generators/no-tests/_notebook.py
dp_wizard/utils/converters.py
tests/utils/test_converters.py

- Fix #305
Code review is sufficient, but if you'd like to see the modal, try adding an error at the top of `_notebook.py`. 
Shiny doesn't offer component level testing, and since the app if it's working correctly never hits this code, it's not easy to execute in an end-to-end test. If we need to do that, the solution might be adding functionality which is hidden from the user, or making a mini application just to exercise this.
I don't think that's necessary right now, but that might not be the right call. Could also file an issue and come back to this later.

No silent errors for code gen

---

README-PYPI.md
README.md
tests/test_misc.py
tests/utils/test_argparse_helpers.py

- Fix #330
- Add test to make sure we're in sync.
- Make README-PYPI a strict subset of README: Even having two separate files is a little gratuitous, but let's keep this relatively simple.
- Remove test helper function that is not needed.

Specify the minimum python version in readme

---

dp_wizard/app/results_panel.py

- Fix #380
(If you want to actually exercise this, you'll need to introduce an error in the notebook, like a `0/0` at the top of `_notebook.py`, though I'm not sure you need to be that diligent.)

click outside error modal or hit esc to close

---

.github/workflows/test.yml

- Fix #329
(The required checks for a repo are in the github configuration, not in the source, so this PR thinks it has tests that haven't run; If it passes review, I'll merge and update the configuration.)

Test both pinned and unpinned deps in CI

---

dp_wizard/utils/code_generators/abstract_generator.py
dp_wizard/utils/code_generators/analyses/histogram/__init__.py
dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_expr.py
dp_wizard/utils/code_generators/analyses/mean/__init__.py
dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_expr.py
dp_wizard/utils/code_generators/analyses/mean/no-tests/_mean_query.py
dp_wizard/utils/code_generators/analyses/median/__init__.py
dp_wizard/utils/code_generators/analyses/median/no-tests/_median_expr.py
dp_wizard/utils/code_generators/analyses/median/no-tests/_median_query.py
tests/utils/test_code_generators.py

- Fix #316
Calling it "config" to begin with was a mistake on my part. These are [polars expressions](https://docs.pola.rs/api/python/dev/reference/expressions/index.html), and `expr` is used consistently in our documentation.

config -> expr

---

dp_wizard/app/components/inputs.py

- Fix #385
(In defense of the off-the-shelf widget, the end values are being hidden because there should be another box containing the current value over the slider, and when they would overlap, the endpoints are suppressed. At some point, it might be better to actually make a log scaled slider, instead of CSS hacking the linear scale.)

always show epsilon slider endpoints

---

CHANGELOG.md

This release was irregular because of the long-lived branch, but we won't repeat that.

update changelog for 0.3.1

---

dp_wizard/utils/shared.py

- Fix #367
Mike's suspicion that empty values where we expected numbers in this CSV caused problems is correct, but the error in this case is shallow: This is a helper function that is used to sort the data before plotting. Falling back to 0 is fine.
Exercising the application against badly behaved CSVs is still a todo, but for this particular bug, this fix seems like enough.

fallback to 0.0 if unexpected key

---

.github/ISSUE_TEMPLATE/bug-back.md
.github/ISSUE_TEMPLATE/bug-front.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md
tests/fixtures/string.csv

- Fix #401
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
> - type
> - The issue type that will be automatically added to issues created with this template. Issue types are defined at the organization level and can be used to create a shared syntax across repos.
> - Optional
> - String

Fix `type` in issue template

---

dp_wizard/shiny/__init__.py
dp_wizard/shiny/analysis_panel.py
dp_wizard/shiny/dataset_panel.py
dp_wizard/shiny/results_panel.py
tests/test_app.py

- Fix #32 
... though not actually locking. I think we're ok with a softer model.
- For the tabs where we haven't provided the prereqs, it's still useful to be able to look around and see what the rest of the app looks like.
- For after the release, we want to point out that the epsilon is spent, but since we can't keep people from just restarting the application, it doesn't make sense to lock it down hard.

Show warnings if you jump around tabs

---

dp_wizard/utils/code_generators/analyses/histogram/no-tests/_histogram_query.py

- Fix #255
I think this came out of a conversation with Cheng Shi or Ellen: The default name of `len` is a little obscure.

in histogram results, rename len to count

---

dp_wizard/shiny/results_panel.py
dp_wizard/utils/code_generators/abstract_generator.py

- Towards #371
- Means and medians still need work.
Motivation: When making example code for the user, we don't want to use unnecessary features, or weaken any of our privacy assumptions. Histograms don't need margins, so we shouldn't include them where they aren't necessary.

Histograms do not need margins

---

dp_wizard/shiny/analysis_panel.py

- Fix #510
`analysis_panel.py` used this logic to determine whether to enable the download button:
```
column_ids_selected = input.columns_selectize()
return len(column_ids_selected) > 0
```
but `results_panel.py` uses this:
```
disabled = not weights()
```
It seems like in automated testing it must be possible for a column to be selected, but for a fraction of a second the weights aren't updated. Hope that using `weights()` everywhere will fix the race condition.

Fix race condition in playwright tests, hopefully

---

README-PYPI.md
README.md
dp_wizard/utils/code_generators/abstract_generator.py
dp_wizard/utils/code_generators/no-tests/_notebook.py
dp_wizard/utils/code_generators/no-tests/_script.py

- Fix #391, I think.
- Replaces #392: Trying to sniff the OS and generating different notebook content is too complicated!
- I realized the instructions in the README also need to be fixed: Without quotes, the `[]` are treated as metacharacters by bash.
For the reviewer: Do these explanations seem useful, without being a distraction for non-windows users?

better docs about quoting for Windows users

---

README.md

Happy to revise wording, and expand the list, if there are particular projects to point to. 
(Do we even want to have a list like this? I think being able to point at other projects in the same space can inspire some confidence in the user that they've found a good option.)
- fix #610

link to blog posts and other projects
